[build]
  base: "/opt/build/repo/TODO"
  command: "ng build"
  commandOrigin: "config"
  publish: "/opt/build/repo/TODO/dist/TODO"
  publishOrigin: "config"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200